[package]
name = "julia"
version = "0.1.0"
edition = "2018"

[dependencies]
num-complex = "0.4"
image = "0.23.14"
palette = "0.6"
libm = "0.2.1"
rayon = "1.5.1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

